import type {
  Bonsai,
  ContextPacket,
  LLMChunk,
  Retriever,
  RetrieverHit,
  Project,
  Branch,
  Merge,
  Message,
  Distillation,
  AuditTrace,
  Id,
} from '@bonsai/core';
import { HttpValidationError } from './errors.js';

export interface HandlerDeps {
  bonsai: Bonsai;
  /** Optional retriever. If absent, the retrieve handler returns 501. */
  retriever?: Retriever;
}

export interface CreateProjectRequest {
  name: string;
  description?: string;
}

export interface CreateBranchRequest {
  fromBranchId: Id;
  forkPoint: Id | null;
  name?: string;
  pinnedAgent?: string | null;
}

export interface ChatRequest {
  branchId: Id;
  message: string;
  tokenBudget?: number;
  keywords?: string;
  model?: string;
}

export interface MergeRequest {
  sourceBranchId: Id;
  targetBranchId: Id;
  /**
   * If provided, the merge summary generated by the LLM is REPLACED with this
   * text before being applied. The `editSummary` hook on the façade takes a
   * function; the HTTP surface only supports a static override because a
   * callback cannot cross a request boundary.
   */
  overrideSummary?: string;
}

export interface DistillRequest {
  branchId?: Id;
  mergeId?: Id;
}

export interface InspectContextRequest {
  branchId: Id;
  tokenBudget?: number;
  keywords?: string;
  model?: string;
}

export interface RetrieveRequest {
  query: string;
  limit?: number;
}

function requireString(v: unknown, field: string): string {
  if (typeof v !== 'string' || v.length === 0) {
    throw new HttpValidationError(`field "${field}" must be a non-empty string`);
  }
  return v;
}

function optionalString(v: unknown, field: string): string | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v !== 'string') {
    throw new HttpValidationError(`field "${field}" must be a string`);
  }
  return v;
}

function optionalNumber(v: unknown, field: string): number | undefined {
  if (v === undefined || v === null) return undefined;
  if (typeof v !== 'number' || !Number.isFinite(v)) {
    throw new HttpValidationError(`field "${field}" must be a finite number`);
  }
  return v;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

export function parseCreateProject(body: unknown): CreateProjectRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const req: CreateProjectRequest = { name: requireString(body.name, 'name') };
  const description = optionalString(body.description, 'description');
  if (description !== undefined) req.description = description;
  return req;
}

export function parseCreateBranch(body: unknown): CreateBranchRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const fromBranchId = requireString(body.fromBranchId, 'fromBranchId');
  let forkPoint: Id | null;
  if (body.forkPoint === null) {
    forkPoint = null;
  } else if (typeof body.forkPoint === 'string') {
    forkPoint = body.forkPoint;
  } else {
    throw new HttpValidationError('field "forkPoint" must be a string or null');
  }
  const req: CreateBranchRequest = { fromBranchId, forkPoint };
  const name = optionalString(body.name, 'name');
  if (name !== undefined) req.name = name;
  if (body.pinnedAgent === null) {
    req.pinnedAgent = null;
  } else {
    const pinnedAgent = optionalString(body.pinnedAgent, 'pinnedAgent');
    if (pinnedAgent !== undefined) req.pinnedAgent = pinnedAgent;
  }
  return req;
}

export function parseChat(body: unknown): ChatRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const req: ChatRequest = {
    branchId: requireString(body.branchId, 'branchId'),
    message: requireString(body.message, 'message'),
  };
  const tokenBudget = optionalNumber(body.tokenBudget, 'tokenBudget');
  if (tokenBudget !== undefined) req.tokenBudget = tokenBudget;
  const keywords = optionalString(body.keywords, 'keywords');
  if (keywords !== undefined) req.keywords = keywords;
  const model = optionalString(body.model, 'model');
  if (model !== undefined) req.model = model;
  return req;
}

export function parseMerge(body: unknown): MergeRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const req: MergeRequest = {
    sourceBranchId: requireString(body.sourceBranchId, 'sourceBranchId'),
    targetBranchId: requireString(body.targetBranchId, 'targetBranchId'),
  };
  const overrideSummary = optionalString(body.overrideSummary, 'overrideSummary');
  if (overrideSummary !== undefined) req.overrideSummary = overrideSummary;
  return req;
}

export function parseDistill(body: unknown): DistillRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const branchId = optionalString(body.branchId, 'branchId');
  const mergeId = optionalString(body.mergeId, 'mergeId');
  if ((branchId === undefined) === (mergeId === undefined)) {
    throw new HttpValidationError('exactly one of "branchId" or "mergeId" is required');
  }
  const req: DistillRequest = {};
  if (branchId !== undefined) req.branchId = branchId;
  if (mergeId !== undefined) req.mergeId = mergeId;
  return req;
}

export function parseInspectContext(body: unknown): InspectContextRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const req: InspectContextRequest = { branchId: requireString(body.branchId, 'branchId') };
  const tokenBudget = optionalNumber(body.tokenBudget, 'tokenBudget');
  if (tokenBudget !== undefined) req.tokenBudget = tokenBudget;
  const keywords = optionalString(body.keywords, 'keywords');
  if (keywords !== undefined) req.keywords = keywords;
  const model = optionalString(body.model, 'model');
  if (model !== undefined) req.model = model;
  return req;
}

export function parseRetrieve(body: unknown): RetrieveRequest {
  if (!isRecord(body)) throw new HttpValidationError('body must be an object');
  const req: RetrieveRequest = { query: requireString(body.query, 'query') };
  const limit = optionalNumber(body.limit, 'limit');
  if (limit !== undefined) req.limit = limit;
  return req;
}

export async function handleCreateProject(
  deps: HandlerDeps,
  input: CreateProjectRequest,
): Promise<Project> {
  return deps.bonsai.createProject(input);
}

export async function handleCreateBranch(
  deps: HandlerDeps,
  input: CreateBranchRequest,
): Promise<Branch> {
  return deps.bonsai.createBranch(input);
}

export function handleChat(
  deps: HandlerDeps,
  input: ChatRequest,
): AsyncIterable<LLMChunk> {
  const { branchId, message, ...rest } = input;
  return deps.bonsai.chat(branchId, message, rest);
}

export async function handleMerge(
  deps: HandlerDeps,
  input: MergeRequest,
): Promise<{ merge: Merge; appliedMessage: Message }> {
  const { overrideSummary, ...core } = input;
  return deps.bonsai.merge({
    ...core,
    ...(overrideSummary !== undefined
      ? { editSummary: (): string => overrideSummary }
      : {}),
  });
}

export async function handleDistill(
  deps: HandlerDeps,
  input: DistillRequest,
): Promise<Distillation> {
  return deps.bonsai.distill(input);
}

export async function handleInspectContext(
  deps: HandlerDeps,
  input: InspectContextRequest,
): Promise<ContextPacket> {
  const { branchId, ...rest } = input;
  return deps.bonsai.assembleContext(branchId, rest);
}

export async function handleRetrieve(
  deps: HandlerDeps,
  input: RetrieveRequest,
): Promise<RetrieverHit[]> {
  if (!deps.retriever) {
    throw new HttpNotImplementedError('retrieve endpoint requires a Retriever adapter');
  }
  return deps.retriever.search(
    input.query,
    input.limit !== undefined ? { limit: input.limit } : undefined,
  );
}

export async function handleResolveTrace(
  deps: HandlerDeps,
  wikiSlug: string,
): Promise<AuditTrace | null> {
  return deps.bonsai.resolveTrace(wikiSlug);
}

export class HttpNotImplementedError extends Error {
  readonly status = 501;
  constructor(message: string) {
    super(message);
    this.name = 'HttpNotImplementedError';
  }
}
